import Head from 'next/head';
import Home from './Components/Home';

const Index = () => {
  return (
    <div>
      <Head>
        <title>Legacy song</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  )
}

export default Index;

