import Head from 'next/head'
import styles from '../styles/Home.module.css'
import DJImage from '../public/images/10_dj.png'


export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.heading}>
          <div className={styles.details}>
            <div className={styles.title}>
              <h1>The Legacy playlist</h1>
              <p>Listen To The Music</p>
            </div>
            <form className={styles.musicForm}>
              <button type="button">
                <label 
                  htmlFor="fileElem"
                >
                  Select Song
                </label>
              </button>
              <span>or drop a file</span>
              <input
                type="file"
                id="fileElem"
                multiple
                accept="audio/mp3"
                onChange={() => console.log("You changed me")}
                onDragEnter={() => console.log("You drag me")}
                onDragOver={() => console.log("You drag me")}
                onDragLeave={() => console.log("You drag me")}
                onDrop={() => console.log("You drag me")}
                />
            </form>
          </div>
          <img
            src={DJImage.src}
            alt="New DJ"
          />

        </section>
      </main>
    </div>
  )
}
